import Foundation
import Cocoa

public enum Attribute: String, CaseIterable {
    case RoleAttribute
    case SubroleAttribute
    case RoleDescriptionAttribute
    case HelpAttribute
    case TitleAttribute
    case ValueAttribute
    case ValueDescriptionAttribute
    case MinValueAttribute
    case MaxValueAttribute
    case ValueIncrementAttribute
    case AllowedValuesAttribute
    case PlaceholderValueAttribute
    case EnabledAttribute
    case ElementBusyAttribute
    case FocusedAttribute
    case ParentAttribute
    case ChildrenAttribute
    case SelectedChildrenAttribute
    case VisibleChildrenAttribute
    case WindowAttribute
    case TopLevelUIElementAttribute
    case PositionAttribute
    case SizeAttribute
    case OrientationAttribute
    case DescriptionAttribute
    case Description // old name
    case SelectedTextAttribute
    case SelectedTextRangeAttribute
    case SelectedTextRangesAttribute
    case VisibleCharacterRangeAttribute
    case NumberOfCharactersAttribute
    case SharedTextUIElementsAttribute
    case SharedCharacterRangeAttribute
    case SharedFocusElementsAttribute
    case InsertionPointLineNumberAttribute
    case MainAttribute
    case MinimizedAttribute
    case CloseButtonAttribute
    case ZoomButtonAttribute
    case MinimizeButtonAttribute
    case ToolbarButtonAttribute
    case FullScreenButtonAttribute
    case ProxyAttribute
    case GrowAreaAttribute
    case ModalAttribute
    case DefaultButtonAttribute
    case CancelButtonAttribute
    case MenuItemCmdCharAttribute
    case MenuItemCmdVirtualKeyAttribute
    case MenuItemCmdGlyphAttribute
    case MenuItemCmdModifiersAttribute
    case MenuItemMarkCharAttribute
    case MenuItemPrimaryUIElementAttribute
    case MenuBarAttribute
    case WindowsAttribute
    case FrontmostAttribute
    case HiddenAttribute
    case MainWindowAttribute
    case FocusedWindowAttribute
    case FocusedUIElementAttribute
    case ExtrasMenuBarAttribute
    case HeaderAttribute
    case EditedAttribute
    case ValueWrapsAttribute
    case TabsAttribute
    case TitleUIElementAttribute
    case HorizontalScrollBarAttribute
    case VerticalScrollBarAttribute
    case OverflowButtonAttribute
    case FilenameAttribute
    case ExpandedAttribute
    case SelectedAttribute
    case SplittersAttribute
    case NextContentsAttribute
    case DocumentAttribute
    case DecrementButtonAttribute
    case IncrementButtonAttribute
    case PreviousContentsAttribute
    case ContentsAttribute
    case IncrementorAttribute
    case HourFieldAttribute
    case MinuteFieldAttribute
    case SecondFieldAttribute
    case AMPMFieldAttribute
    case DayFieldAttribute
    case MonthFieldAttribute
    case YearFieldAttribute
    case ColumnTitleAttribute
    case URLAttribute
    case LabelUIElementsAttribute
    case LabelValueAttribute
    case ShownMenuUIElementAttribute
    case ServesAsTitleForUIElementsAttribute
    case LinkedUIElementsAttribute
    case RowsAttribute
    case VisibleRowsAttribute
    case SelectedRowsAttribute
    case ColumnsAttribute
    case VisibleColumnsAttribute
    case SelectedColumnsAttribute
    case SortDirectionAttribute
    case IndexAttribute
    case DisclosingAttribute
    case DisclosedRowsAttribute
    case DisclosedByRowAttribute
    case DisclosureLevelAttribute
    case MatteHoleAttribute
    case MatteContentUIElementAttribute
    case MarkerUIElementsAttribute
    case UnitsAttribute
    case UnitDescriptionAttribute
    case MarkerTypeAttribute
    case MarkerTypeDescriptionAttribute
    case IsApplicationRunningAttribute
    case SearchButtonAttribute
    case ClearButtonAttribute
    case FocusedApplicationAttribute
    case RowCountAttribute
    case ColumnCountAttribute
    case OrderedByRowAttribute
    case WarningValueAttribute
    case CriticalValueAttribute
    case SelectedCellsAttribute
    case VisibleCellsAttribute
    case RowHeaderUIElementsAttribute
    case ColumnHeaderUIElementsAttribute
    case RowIndexRangeAttribute
    case ColumnIndexRangeAttribute
    case HorizontalUnitsAttribute
    case VerticalUnitsAttribute
    case HorizontalUnitDescriptionAttribute
    case VerticalUnitDescriptionAttribute
    case HandlesAttribute
    case TextAttribute
    case VisibleTextAttribute
    case IsEditableAttribute
    case ColumnTitlesAttribute
    case IdentifierAttribute
    case AlternateUIVisibleAttribute
    case LineForIndexParameterizedAttribute
    case RangeForLineParameterizedAttribute
    case StringForRangeParameterizedAttribute
    case RangeForPositionParameterizedAttribute
    case RangeForIndexParameterizedAttribute
    case BoundsForRangeParameterizedAttribute
    case RTFForRangeParameterizedAttribute
    case AttributedStringForRangeParameterizedAttribute
    case StyleRangeForIndexParameterizedAttribute
    case CellForColumnAndRowParameterizedAttribute
    case LayoutPointForScreenPointParameterizedAttribute
    case LayoutSizeForScreenSizeParameterizedAttribute
    case ScreenPointForLayoutPointParameterizedAttribute
    case ScreenSizeForLayoutSizeParameterizedAttribute
    
    var attribute: String {
        switch self {
        case .RoleAttribute:
            return kAXRoleAttribute
        case .SubroleAttribute:
            return kAXSubroleAttribute
        case .RoleDescriptionAttribute:
            return kAXRoleDescriptionAttribute
        case .TitleAttribute:
            return kAXTitleAttribute
        case .DescriptionAttribute:
            return kAXDescriptionAttribute
        case .HelpAttribute:
            return kAXHelpAttribute
        case .ParentAttribute:
            return kAXParentAttribute
        case .ChildrenAttribute:
            return kAXChildrenAttribute
        case .SelectedChildrenAttribute:
            return kAXSelectedChildrenAttribute
        case .VisibleChildrenAttribute:
            return kAXVisibleChildrenAttribute
        case .WindowAttribute:
            return kAXWindowAttribute
        case .TopLevelUIElementAttribute:
            return kAXTopLevelUIElementAttribute
        case .TitleUIElementAttribute:
            return kAXTitleUIElementAttribute
        case .ServesAsTitleForUIElementsAttribute:
            return kAXServesAsTitleForUIElementsAttribute
        case .LinkedUIElementsAttribute:
            return kAXLinkedUIElementsAttribute
        case .SharedFocusElementsAttribute:
            return kAXSharedFocusElementsAttribute
        case .EnabledAttribute:
            return kAXEnabledAttribute
        case .FocusedAttribute:
            return kAXFocusedAttribute
        case .PositionAttribute:
            return kAXPositionAttribute
        case .SizeAttribute:
            return kAXSizeAttribute
        case .ValueAttribute:
            return kAXValueAttribute
        case .ValueDescriptionAttribute:
            return kAXValueDescriptionAttribute
        case .MinValueAttribute:
            return kAXMinValueAttribute
        case .MaxValueAttribute:
            return kAXMaxValueAttribute
        case .ValueIncrementAttribute:
            return kAXValueIncrementAttribute
        case .ValueWrapsAttribute:
            return kAXValueWrapsAttribute
        case .AllowedValuesAttribute:
            return kAXAllowedValuesAttribute
        case .SelectedTextAttribute:
            return kAXSelectedTextAttribute
        case .SelectedTextRangeAttribute:
            return kAXSelectedTextRangeAttribute
        case .SelectedTextRangesAttribute:
            return kAXSelectedTextRangesAttribute
        case .VisibleCharacterRangeAttribute:
            return kAXVisibleCharacterRangeAttribute
        case .NumberOfCharactersAttribute:
            return kAXNumberOfCharactersAttribute
        case .SharedTextUIElementsAttribute:
            return kAXSharedTextUIElementsAttribute
        case .SharedCharacterRangeAttribute:
            return kAXSharedCharacterRangeAttribute
        case .MainAttribute:
            return kAXMainAttribute
        case .MinimizedAttribute:
            return kAXMinimizedAttribute
        case .CloseButtonAttribute:
            return kAXCloseButtonAttribute
        case .ZoomButtonAttribute:
            return kAXZoomButtonAttribute
        case .MinimizeButtonAttribute:
            return kAXMinimizeButtonAttribute
        case .ToolbarButtonAttribute:
            return kAXToolbarButtonAttribute
        case .ProxyAttribute:
            return kAXProxyAttribute
        case .GrowAreaAttribute:
            return kAXGrowAreaAttribute
        case .ModalAttribute:
            return kAXModalAttribute
        case .DefaultButtonAttribute:
            return kAXDefaultButtonAttribute
        case .CancelButtonAttribute:
            return kAXCancelButtonAttribute
        case .MenuItemCmdCharAttribute:
            return kAXMenuItemCmdCharAttribute
        case .MenuItemCmdVirtualKeyAttribute:
            return kAXMenuItemCmdVirtualKeyAttribute
        case .MenuItemCmdGlyphAttribute:
            return kAXMenuItemCmdGlyphAttribute
        case .MenuItemCmdModifiersAttribute:
            return kAXMenuItemCmdModifiersAttribute
        case .MenuItemMarkCharAttribute:
            return kAXMenuItemMarkCharAttribute
        case .MenuItemPrimaryUIElementAttribute:
            return kAXMenuItemPrimaryUIElementAttribute
        case .MenuBarAttribute:
            return kAXMenuBarAttribute
        case .WindowsAttribute:
            return kAXWindowAttribute
        case .FrontmostAttribute:
            return kAXFrontmostAttribute
        case .HiddenAttribute:
            return kAXHiddenAttribute
        case .MainWindowAttribute:
            return kAXMainWindowAttribute
        case .FocusedWindowAttribute:
            return kAXFocusedWindowAttribute
        case .FocusedUIElementAttribute:
            return kAXFocusedUIElementAttribute
        case .ExtrasMenuBarAttribute:
            return kAXExtrasMenuBarAttribute
        case .HourFieldAttribute:
            return kAXHourFieldAttribute
        case .MinuteFieldAttribute:
            return kAXMinuteFieldAttribute
        case .SecondFieldAttribute:
            return kAXSecondFieldAttribute
        case .AMPMFieldAttribute:
            return kAXAMPMFieldAttribute
        case .DayFieldAttribute:
            return kAXDayFieldAttribute
        case .MonthFieldAttribute:
            return kAXMonthFieldAttribute
        case .YearFieldAttribute:
            return kAXYearFieldAttribute
        case .RowsAttribute:
            return kAXRowsAttribute
        case .VisibleRowsAttribute:
            return kAXVisibleRowsAttribute
        case .SelectedRowsAttribute:
            return kAXSelectedRowsAttribute
        case .ColumnsAttribute:
            return kAXColumnsAttribute
        case .VisibleColumnsAttribute:
            return kAXVisibleColumnsAttribute
        case .SelectedColumnsAttribute:
            return kAXSelectedColumnsAttribute
        case .SortDirectionAttribute:
            return kAXSortDirectionAttribute
        case .ColumnHeaderUIElementsAttribute:
            return kAXColumnHeaderUIElementsAttribute
        case .IndexAttribute:
            return kAXIndexAttribute
        case .DisclosingAttribute:
            return kAXDisclosingAttribute
        case .DisclosedRowsAttribute:
            return kAXDisclosedRowsAttribute
        case .DisclosedByRowAttribute:
            return kAXDisclosedByRowAttribute
        case .MatteHoleAttribute:
            return kAXMatteHoleAttribute
        case .MatteContentUIElementAttribute:
            return kAXMatteContentUIElementAttribute
        case .MarkerUIElementsAttribute:
            return kAXMarkerUIElementsAttribute
        case .UnitsAttribute:
            return kAXUnitsAttribute
        case .UnitDescriptionAttribute:
            return kAXUnitDescriptionAttribute
        case .MarkerTypeAttribute:
            return kAXMarkerTypeAttribute
        case .MarkerTypeDescriptionAttribute:
            return kAXMarkerTypeDescriptionAttribute
        case .HorizontalScrollBarAttribute:
            return kAXHorizontalScrollBarAttribute
        case .VerticalScrollBarAttribute:
            return kAXVerticalScrollBarAttribute
        case .OrientationAttribute:
            return kAXOrientationAttribute
        case .HeaderAttribute:
            return kAXHeaderAttribute
        case .EditedAttribute:
            return kAXEditedAttribute
        case .TabsAttribute:
            return kAXTabsAttribute
        case .OverflowButtonAttribute:
            return kAXOverflowButtonAttribute
        case .FilenameAttribute:
            return kAXFilenameAttribute
        case .ExpandedAttribute:
            return kAXExpandedAttribute
        case .SelectedAttribute:
            return kAXSelectedAttribute
        case .SplittersAttribute:
            return kAXSplittersAttribute
        case .ContentsAttribute:
            return kAXContentsAttribute
        case .NextContentsAttribute:
            return kAXNextContentsAttribute
        case .PreviousContentsAttribute:
            return kAXPreviousContentsAttribute
        case .DocumentAttribute:
            return kAXDocumentAttribute
        case .IncrementorAttribute:
            return kAXIncrementorAttribute
        case .DecrementButtonAttribute:
            return kAXDecrementButtonAttribute
        case .IncrementButtonAttribute:
            return kAXIncrementButtonAttribute
        case .ColumnTitleAttribute:
            return kAXColumnTitleAttribute
        case .URLAttribute:
            return kAXURLAttribute
        case .LabelUIElementsAttribute:
            return kAXLabelUIElementsAttribute
        case .LabelValueAttribute:
            return kAXLabelValueAttribute
        case .ShownMenuUIElementAttribute:
            return kAXShownMenuUIElementAttribute
        case .IsApplicationRunningAttribute:
            return kAXIsApplicationRunningAttribute
        case .FocusedApplicationAttribute:
            return kAXFocusedApplicationAttribute
        case .ElementBusyAttribute:
            return kAXElementBusyAttribute
        case .AlternateUIVisibleAttribute:
            return kAXAlternateUIVisibleAttribute
        case .PlaceholderValueAttribute:
            return kAXPlaceholderValueAttribute
        case .Description:
            return kAXDescription
        case .InsertionPointLineNumberAttribute:
            return kAXInsertionPointLineNumberAttribute
        case .FullScreenButtonAttribute:
            return kAXFullScreenButtonAttribute
        case .DisclosureLevelAttribute:
            return kAXDisclosureLevelAttribute
        case .SearchButtonAttribute:
            return kAXSearchButtonAttribute
        case .ClearButtonAttribute:
            return kAXClearButtonAttribute
        case .RowCountAttribute:
            return kAXRowCountAttribute
        case .ColumnCountAttribute:
            return kAXColumnCountAttribute
        case .OrderedByRowAttribute:
            return kAXOrderedByRowAttribute
        case .WarningValueAttribute:
            return kAXWarningValueAttribute
        case .CriticalValueAttribute:
            return kAXCriticalValueAttribute
        case .SelectedCellsAttribute:
            return kAXSelectedCellsAttribute
        case .VisibleCellsAttribute:
            return kAXVisibleCellsAttribute
        case .RowHeaderUIElementsAttribute:
            return kAXRowHeaderUIElementsAttribute
        case .RowIndexRangeAttribute:
            return kAXRowIndexRangeAttribute
        case .ColumnIndexRangeAttribute:
            return kAXColumnIndexRangeAttribute
        case .HorizontalUnitsAttribute:
            return kAXHorizontalUnitsAttribute
        case .VerticalUnitsAttribute:
            return kAXVerticalUnitsAttribute
        case .HorizontalUnitDescriptionAttribute:
            return kAXHorizontalUnitDescriptionAttribute
        case .VerticalUnitDescriptionAttribute:
            return kAXVerticalUnitDescriptionAttribute
        case .HandlesAttribute:
            return kAXHandlesAttribute
        case .TextAttribute:
            return kAXTextAttribute
        case .VisibleTextAttribute:
            return kAXVisibleTextAttribute
        case .IsEditableAttribute:
            return kAXIsEditableAttribute
        case .ColumnTitlesAttribute:
            return kAXColumnTitleAttribute
        case .IdentifierAttribute:
            return kAXIdentifierAttribute
        case .LineForIndexParameterizedAttribute:
            return kAXLineForIndexParameterizedAttribute
        case .RangeForLineParameterizedAttribute:
            return kAXRangeForLineParameterizedAttribute
        case .StringForRangeParameterizedAttribute:
            return kAXStringForRangeParameterizedAttribute
        case .RangeForPositionParameterizedAttribute:
            return kAXRangeForPositionParameterizedAttribute
        case .RangeForIndexParameterizedAttribute:
            return kAXRangeForIndexParameterizedAttribute
        case .BoundsForRangeParameterizedAttribute:
            return kAXBoundsForRangeParameterizedAttribute
        case .RTFForRangeParameterizedAttribute:
            return kAXRTFForRangeParameterizedAttribute
        case .AttributedStringForRangeParameterizedAttribute:
            return kAXAttributedStringForRangeParameterizedAttribute
        case .StyleRangeForIndexParameterizedAttribute:
            return kAXStyleRangeForIndexParameterizedAttribute
        case .CellForColumnAndRowParameterizedAttribute:
            return kAXCellForColumnAndRowParameterizedAttribute
        case .LayoutPointForScreenPointParameterizedAttribute:
            return kAXLayoutPointForScreenPointParameterizedAttribute
        case .LayoutSizeForScreenSizeParameterizedAttribute:
            return kAXLayoutSizeForScreenSizeParameterizedAttribute
        case .ScreenPointForLayoutPointParameterizedAttribute:
            return kAXScreenPointForLayoutPointParameterizedAttribute
        case .ScreenSizeForLayoutSizeParameterizedAttribute:
            return kAXScreenSizeForLayoutSizeParameterizedAttribute
        }
    }
}
